### PR TITLE
added some new changes to index.html for git-tst

### LINKED ISSUE #18: Add merge conflicts and resolve them!

### PR DESCRIPTION
**Pull request by Squishy123**
# What do you think of these changes?!?
closes #18

### CODE REVIEW

**Review by JoseArnel — COMMENTED** [review]
Nice Changes!

**Review by JoseArnel — APPROVED** [review]
Looks great!

**Comment by OneHandKlap** [comment]
Jose you truly are cool and special!

**Review by OneHandKlap — COMMENTED** [review]
True af.

**Comment by taimoorgit** [comment]
Based

**Pull request merged**
